# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CropFrame_Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CropFrame_Example
  pod 'CropFrame', '~> 0.0.1'
end
